### PR TITLE
Boolean Attributes Query support , dependencies update, security update, SNMP V3 Support

### PR DESCRIPTION
**Pull request by eczema**
- To be compliant with Mysql AND Postgresql , boolean type require 'is true' instead of ' = 1' 
 -  NOT translated as 'is false' for boolean  

see issue https://github.com/netfishers-onl/Netshot/issues/27

### CODE REVIEW

**Comment by eczema** [comment]
image

**Comment by eczema** [comment]
image

**Comment by SCadilhac** [comment]
Library versions have been updated. Fix committed for finder.
In regards to SNMPv3 commits:
* the code is not properly formatted (indentation, variable names, etc.)
* the max size of the device_credential_set table is reached in MySQL due to the additional columns
* some cleanup and optimisation might be needed

**Comment by eczema** [comment]
> Library versions have been updated. Fix committed for finder.
> In regards to SNMPv3 commits:
> 
>     * the code is not properly formatted (indentation, variable names, etc.)
> 
For sure.... 
>     * the max size of the device_credential_set table is reached in MySQL due to the additional columns
Just for 5 more columns ? how to handle this problem ? 
> 
>     * some cleanup and optimisation might be needed

**Comment by SCadilhac** [comment]
> Just for 5 more columns ? how to handle this problem ?

Simplest way is to reduce the size of the `privateKey` and `publicKey` fields. But unfortunately Hibernate schema auto-update feature doesn't seem to properly handle the column size reduction. It's probably time to integrate a customized database upgrade mechanism at Netshot startup.

**Comment by SCadilhac** [comment]
The features have been manually integrated.

**Pull request closed without merging**
